# Generated by Django 4.1.6 on 2023-05-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0002_ricsponsor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OurSponsor",
        ),
    ]
