# Generated by Django 4.1.6 on 2023-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0003_delete_oursponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ricsponsor",
            name="order",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
