# Generated by Django 4.1.6 on 2023-05-03 15:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "members",
            "0018_remove_ic_icsubmission_remove_ic_icsubmissionformat_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("pic", models.ImageField(upload_to="event")),
                ("subtitle", models.CharField(max_length=50)),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("subtitle", ckeditor.fields.RichTextField()),
                ("pic", models.ImageField(upload_to="speakers")),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="DeptSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("subtitle", ckeditor.fields.RichTextField()),
                ("pic", models.ImageField(upload_to="dept_speakers")),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.dept",
                    ),
                ),
            ],
        ),
    ]
