# Generated by Django 4.1.6 on 2023-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deptspeaker",
            name="dept",
        ),
    ]
