# Generated by Django 4.1.6 on 2023-05-06 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0018_remove_ic_icsubmission_remove_ic_icsubmissionformat_and_more",
        ),
        ("event", "0002_remove_deptspeaker_dept"),
    ]

    operations = [
        migrations.AddField(
            model_name="deptspeaker",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.dept",
            ),
        ),
    ]
